### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by akkshaylawrence** [tomkthomas/tomkthomas-bling#2]
I looked into your deployment and the app looks fine to me. Good work on that!
I have some suggestions regarding styling that you can do to make it even better.
- The major thing I'm seeing are issues with the layout, mainly in how the dashboard displays cards and where the card maker is displayed.
- I'm also seeing differences in the font but I may be wrong on that one.

**Comment by tomkthomas** [comment]
> I looked into your deployment and the app looks fine to me. Good work on that!
> I have some suggestions regarding styling that you can do to make it even better.
> 
>     * The major thing I'm seeing are issues with the layout, mainly in how the dashboard displays cards and where the card maker is displayed.
> 
>     * I'm also seeing differences in the font but I may be wrong on that one.

I have made changes in the layout and changed the font.

**Comment by tomkthomas** [comment]
Please check if anymore changes is required
